
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase';

const SUPABASE_URL = "https://etdzhpnqxwcfqbhdacsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0ZHpocG5xeHdjZnFiaGRhY3NhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyOTE1NTcsImV4cCI6MjA1OTg2NzU1N30.-9vw1IRCXs9WKkdJVIAJQKoTIvBn1IM5aZMA_El25f8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
